import type { DailyFeedEntry } from './trendTypes';

export const publicDailyFeedHistory: DailyFeedEntry[] = [
  {
    id: 'feed-2026-05-28',
    isoDate: '2026-05-28',
    date: 'May 28, 2026',
    displayDate: '05/28 Thursday',
    trends: [
      {
        id: 'digest-adopt-me-potions-loop',
        title: 'Adopt Me potion-and-pet loop',
        category: 'Games',
        signal: "Adopt Me's May 2026 updates kept stacking fresh reasons to check back, including new weather needs, a potion system, and this week's Stormy Ducky Drama event on the official site and Roblox game page. Common Sense Media still describes it as one of Roblox's biggest games, with more than 28 billion visits, and current Reddit discussion is still deep into potion math, dream-pet trading, and update spoilers rather than treating it like old news.",
        meaning: 'The hook is not only cute pets anymore. For a lot of kids, Adopt Me is now a recurring routine game: raise pets, optimize aging, chase limited drops, and compare progress with friends who understand the same economy.',
        parentTranslation: 'Think digital pet care crossed with a time-and-trade economy. Kids can sound like they are talking about toys, but the real draw is often keeping up with update cycles, values, and streak-like momentum.',
        askPrompt: 'When you want to play Adopt Me right now, what matters most: taking care of pets, making neons, or trading for something everyone else wants?',
        watchOut: 'Watch Robux pressure, trade scams, and how often the game starts feeling like a chore to keep up with. Roblox is rolling out more kid-specific account controls, but families still need to check chat and spending settings closely.',
        ageBand: 'Kids + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-mario-kart-world-default-party-game',
        title: 'Mario Kart World stays the default party game',
        category: 'Games',
        signal: 'Nintendo is still positioning Mario Kart World as the wide-audience anchor for Switch 2, with local play, couch multiplayer, online races, and assistive driving options all highlighted on the official game page. Nintendo reporting around May 11, 2026 still had it as the best-selling Switch 2 game at 14.70 million copies, while current Reddit bundle chatter keeps treating it as the obvious family pick when parents or relatives buy the system.',
        meaning: 'This is less a niche gamer trend than a shared household default. Kids do not need deep game knowledge to join, so it keeps resurfacing at sleepovers, sibling hangouts, and family gatherings as the game everyone can agree on.',
        parentTranslation: 'Mario Kart is acting like a social appliance again. The cultural value is not only the races themselves; it is being the easiest way for a group of mixed ages and skill levels to play the same thing together.',
        askPrompt: 'If kids keep asking for Mario Kart, is it mostly about racing, unlocking things, or having a game everyone in the room can actually play together?',
        watchOut: 'The game itself is approachable, but the surrounding spend is not: pricey hardware, extra controllers, online membership, and sibling frustration when competition gets heated. After March 31, 2026, GameChat also requires Nintendo Switch Online.',
        ageBand: 'Kids + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-bluey-destination-event',
        title: 'Bluey is turning into a destination event',
        category: 'Shows & Music',
        signal: "Bluey's official site has been teeing up Disney park activations for summer 2026, and Bluey's Wild World opened at Disney's Animal Kingdom on May 26, 2026. Parent-facing coverage and Disney/Bluey community threads immediately focused on virtual-queue strategy and day-of demand, which is a good clue that Bluey is still big enough to shape real family plans rather than living only as a background comfort show.",
        meaning: 'Bluey is not just a show kids watch at home anymore. It is becoming an experience kids anticipate, talk about, and build outings around, which keeps the fandom active even for families who already know the episodes by heart.',
        parentTranslation: 'This is preschool fandom growing legs in the real world. When a gentle TV favorite becomes a queue-worthy event, it usually means the brand has moved from passive viewing into family identity and ritual.',
        askPrompt: 'If Bluey feels exciting right now, is it because of the episodes themselves, meeting the characters, or doing Bluey-style play in real life?',
        watchOut: 'Mostly a very safe trend, but the practical friction is real: travel cost, merch creep, long waits, and younger kids getting overstimulated if the day starts feeling bigger than the show.',
        ageBand: 'Kids',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
    ],
  },
  {
    id: 'feed-2026-05-27',
    isoDate: '2026-05-27',
    date: 'May 27, 2026',
    displayDate: '05/27 Wednesday',
    trends: [
      {
        id: 'digest-gabbys-dollhouse-expands',
        title: "Gabby's Dollhouse keeps expanding",
        category: 'Shows & Music',
        signal: "Netflix is still pushing fresh 2026 Gabby's Dollhouse episodes, the official app shows 10M+ downloads and a Teacher Approved badge on Google Play, industry coverage says the brand stayed Netflix's top original kids' series worldwide in 2025, and parent/community chatter still treats the movie as a repeat-watch favorite.",
        meaning: "Gabby is working less like a one-show phase and more like a full kid ecosystem: streaming comfort watch, craft-and-unboxing fantasy, app play, toy tie-ins, and recognizable characters that younger kids can bring into pretend play.",
        parentTranslation: 'This is preschool fandom with a long runway. The attraction is not only the show itself, but the feeling that there is always another soft landing spot nearby: the app, the movie, the toys, or the music.',
        askPrompt: 'When kids are into Gabby right now, what do they actually come back for most: the cats, the crafts, the dollhouse world, or the movie songs?',
        watchOut: 'Usually a gentle trend, but check in-app purchase settings, QR-code toy upsells, and whether younger kids are getting overstimulated by the constant merchandise loop more than the story itself.',
        ageBand: 'Kids',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-lol-plush-surprise',
        title: 'L.O.L. Surprise Plush Surprise',
        category: 'Toys & Collectibles',
        signal: 'MGA just launched a new Plush Surprise line built around blind-box reveals and removable bag clips, toy coverage is framing it as a bag-charm crossover, and community chatter picked up quickly around favorite characters, hidden pieces, and later-wave expectations.',
        meaning: 'L.O.L. is adapting to the backpack-charm moment. The hook is not deep doll play alone; it is getting a cute clip-on character, opening little extras, and carrying something friends notice right away.',
        parentTranslation: 'Think collectible plush plus wearable status signal. Kids can treat it like a toy at home and a style badge once it is clipped to a bag.',
        askPrompt: 'Do kids care more about which character they get, the surprise accessories inside, or having something cute clipped to a backpack?',
        watchOut: 'Low-drama overall, but it is still a blind-box spending loop. Watch duplicate disappointment, accessory loss, and whether a harmless bag charm starts turning into constant “just one more” asks.',
        ageBand: 'Kids + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-pokemon-30-wave',
        title: 'Pokemon 30 nostalgia wave',
        category: 'Toys & Collectibles',
        signal: 'Pokemon\'s 30th-anniversary hub is still active, the retro Pikachu plush stayed in demand enough to trigger restock and local-release coverage, and parent/fan chatter keeps turning the anniversary into plush picks, gift lists, and family nostalgia handoffs rather than only card talk.',
        meaning: 'This year\'s Pokemon energy is broader than the usual playground card cycle. Kids are meeting the brand through plush, gifts, anniversary merch, and parent-guided “pick your starter” moments that make the franchise feel current again across ages.',
        parentTranslation: 'This is a nostalgia bridge trend. Parents who grew up with Pokemon suddenly have an easy excuse to pass it down, which makes the requests feel more emotionally loaded than a normal toy ask.',
        askPrompt: 'If Pokemon is popping up right now, is the excitement mostly about cards, plush, a favorite character, or doing something with you that feels like “your old thing” becoming theirs?',
        watchOut: 'The safer versions are plush and low-stakes merch. The pressure rises fast around scarcity, collector pricing, and the way anniversary hype can make ordinary items feel urgent or “special edition.”',
        ageBand: 'Elementary + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
    ],
  },
  {
    id: 'feed-2026-05-26',
    isoDate: '2026-05-26',
    date: 'May 26, 2026',
    displayDate: '05/26 Tuesday',
    trends: [
      {
        id: 'digest-bluey-happy-snaps',
        title: "Bluey's Happy Snaps",
        category: 'Games',
        signal: 'Wishlist chatter about the new Bluey game, kids comparing it to Pokemon Snap, and parents noticing the “no online play, no in-game purchases” pitch',
        meaning: 'Bluey is stretching from comfort-show fandom into game-request territory, with the appeal centered on taking photos, spotting familiar characters, and getting a safer-feeling family game to ask for.',
        parentTranslation: 'This is less a competitive gaming trend and more a low-drama media extension. Kids who already trust Bluey may treat it as an easy first “real game” ask.',
        askPrompt: 'Would you want this because it is Bluey, because it is a camera game, or because it feels like something you could play with a sibling?',
        watchOut: 'Safer than most online game requests, but still worth setting expectations around price, screen time, and whether the excitement is about the actual game or just the Bluey brand.',
        ageBand: 'Kids',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-stitch-everywhere',
        title: 'Stitch-everywhere merch wave',
        category: 'Shows & Music',
        signal: 'Backpack clips, plush, pajamas, character-store talk, and kids still asking for Stitch items well after the live-action movie spike',
        meaning: 'Stitch is acting less like a one-movie character and more like a durable kid style badge: cute, chaotic, recognizable, and easy to wear or clip onto something.',
        parentTranslation: 'For many kids this is not really about plot. It is a character-affinity trend that sits halfway between fandom and fashion accessory.',
        askPrompt: 'What do kids actually want right now: the movie, the plush, the bag charm, or just one character everyone instantly recognizes?',
        watchOut: 'Usually pretty mild, but the buying pressure can spread across lots of small items fast, especially when Stitch gets folded into pajamas, bags, seasonal drops, and sibling matching sets.',
        ageBand: 'Kids + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-dog-man-stays-big',
        title: 'Dog Man still has a grip',
        category: 'Other Kid Culture',
        signal: 'Elementary kids re-reading the books, teachers still seeing strong Dog Man attachment, and fresh chatter around the next book and touring musical',
        meaning: 'Dog Man has settled into that rare lane where it is not just a series kids liked once. It keeps resurfacing as a social reading reference point, especially for younger elementary kids and reluctant readers.',
        parentTranslation: 'This is one of those trends that looks silly from the outside but can genuinely anchor reading motivation and playground conversation at the same time.',
        askPrompt: 'Is Dog Man fun right now because the stories are funny, because friends are reading it too, or because it feels easier to keep up with than longer books?',
        watchOut: 'Usually a net positive trend, but some kids stall there and resist branching out, so it helps to treat Dog Man as a bridge into nearby graphic novels instead of the whole reading diet.',
        ageBand: 'Kids',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
    ],
  },
  {
    id: 'feed-2026-05-25',
    isoDate: '2026-05-25',
    date: 'May 25, 2026',
    displayDate: '05/25 Monday',
    trends: [
      {
        id: 'digest-toca-boca-music',
        title: 'Toca Boca World music drops',
        category: 'Games',
        signal: 'Kids talking about Olivia Rodrigo in Toca Boca, decorating rooms to songs, roleplay scenes built around artist months',
        meaning: 'Toca Boca is folding pop-music fandom into its sandbox app, so the draw is not only open-ended play but using familiar songs to set a vibe and show taste.',
        parentTranslation: 'This is digital dollhouse play with a soundtrack. For some kids, the music matters less as “listening” and more as a badge that their pretend world feels current.',
        askPrompt: 'What do kids actually do with the music player: make story scenes, decorate to match the songs, or mostly show friends which artist month they like?',
        watchOut: 'Useful low-drama trend overall, but keep an eye on pack-purchase pressure, update churn, and whether music fandom is pulling kids from the app into more open social/video spaces.',
        ageBand: 'Kids + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-jellycat-collecting',
        title: 'Jellycat collecting',
        category: 'Toys & Collectibles',
        signal: 'Wishlists, sellout alerts, store hunts, plush “drops,” and kids comparing favorites or harder-to-find characters',
        meaning: 'Jellycat has shifted from simple comfort plush to a light collection culture, where softness still matters but scarcity and finding the “right” character matter too.',
        parentTranslation: 'This is a gentler collectible trend than trading cards or blind boxes, but it still has status energy once kids start chasing specific animals, seasonal launches, or store exclusives.',
        askPrompt: 'Is the appeal mostly cuddly comfort, room decor, or finding the one character that feels special enough to ask for?',
        watchOut: 'Usually low risk, but resellers, price creep, and fast sellouts can turn a sweet plush into a scarcity-and-spending loop if expectations are not set early.',
        ageBand: 'Kids + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-toy-story-5',
        title: 'Toy Story 5 countdown',
        category: 'Shows & Music',
        signal: 'Trailer talk, character rewatching, Lilypad tablet chatter, and families noticing the movie’s toys-versus-tech setup',
        meaning: 'The next Toy Story is landing as both nostalgia bait for parents and fresh excitement for kids, with the new hook centered on play competing with screens.',
        parentTranslation: 'This is less a deep-lore fandom moment than a shared family reference point. It gives parents an easy way into conversations about what still counts as fun, imaginative play.',
        askPrompt: 'Which part is interesting to kids right now: seeing Woody and Buzz again, the new tablet villain, or just having a big summer movie everyone knows?',
        watchOut: 'Probably one of the safer current hype cycles, but younger kids may mostly encounter trailers, shorts, and merch first, so check whether the excitement is about the story or just the marketing loop.',
        ageBand: 'Kids + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
    ],
  },
  {
    id: 'feed-2026-05-24',
    isoDate: '2026-05-24',
    date: 'May 24, 2026',
    displayDate: '05/24 Sunday',
    trends: [
      {
        id: 'digest-brookhaven-rp',
        title: 'Brookhaven roleplay',
        category: 'Games',
        signal: 'Roblox house claims, family roleplay, premium-house status talk, after-school meetups',
        meaning: 'A free-form Roblox town where the point is social roleplay: kids claim houses, act out jobs or families, and mostly use the space to hang out.',
        parentTranslation: 'Think digital dollhouse plus group chat. The draw is less the map itself and more the feeling of meeting friends in a shared pretend world.',
        askPrompt: 'What do kids actually do in Brookhaven right now: decorate houses, roleplay families, or mostly just meet up and chat?',
        watchOut: 'Because the play is so social, check chat settings, Robux pressure around Premium perks, and whether roleplay with strangers is getting weird or intense.',
        ageBand: 'Kids + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-beyblade-x',
        title: 'Beyblade X',
        category: 'Toys & Collectibles',
        signal: 'Launcher talk, stadium battles, part-combo debates, school or sibling tournaments',
        meaning: 'The current Beyblade generation is being treated less like a throwback toy and more like a fast, competitive hobby with parts, strategy, and event buzz.',
        parentTranslation: 'Kids are not only collecting tops. They are comparing builds, practicing launches, and turning it into a mini-sport with status around skill and gear.',
        askPrompt: 'What matters more right now: favorite characters, rare parts, or having the combo that actually wins?',
        watchOut: 'Budget for the stadium-and-launcher ecosystem before extras pile up, and keep play to open spaces where fast parts are not hitting siblings, pets, or breakables.',
        ageBand: 'Elementary + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-bitzee-aquarium',
        title: 'Bitzee Aquarium',
        category: 'Toys & Collectibles',
        signal: 'Touchable digital pets, fish-tank reveals, desk-toy talk, comparison to Tamagotchi-style pets',
        meaning: 'A new Bitzee spin that turns the digital-pet loop into a tactile aquarium: kids feed, tap, and collect animated sea creatures without handing over a phone.',
        parentTranslation: 'This hits the “screen-like but not a screen” sweet spot. It scratches the care-and-collect itch while still feeling like a contained toy.',
        askPrompt: 'Is the fun mostly the petting/feeding part, or comparing which creatures and tank details friends have unlocked?',
        watchOut: 'Probably gentler than app-based pets, but it can still become a collect-them-all purchase trail if kids start chasing every version or accessory.',
        ageBand: 'Kids',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
    ],
  },
  {
    id: 'feed-2026-05-23',
    isoDate: '2026-05-23',
    date: 'May 23, 2026',
    displayDate: '05/23 Saturday',
    trends: [
      {
        id: 'digest-dress-to-impress',
        title: 'Dress to Impress',
        category: 'Games',
        signal: 'Roblox fashion rounds, outfit themes, VIP/code talk, runway voting',
        meaning: 'A fast, social Roblox dress-up game where kids build looks under time pressure and get rated by other players.',
        parentTranslation: 'It is dress-up play mixed with public scoring. The draw is showing taste and knowing the references, not just winning.',
        askPrompt: 'What themes are fun right now, and do kids care more about creativity or getting votes?',
        watchOut: 'Check chat settings, spending on VIP/items, and whether public scoring is turning the game mean or stressful.',
        ageBand: 'Kids + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-needoh-hunting',
        title: 'NeeDoh hunting',
        category: 'Toys & Collectibles',
        signal: 'Squishy fidgets, variant names, restock hunts, backpack/classroom swapping',
        meaning: 'A fidget-toy craze driven by texture, collecting, and the social hunt for sold-out versions.',
        parentTranslation: 'The squish itself matters, but the bigger social signal is finding the hard-to-get one before everyone else does.',
        askPrompt: 'Which version feels different enough that kids keep looking for more?',
        watchOut: 'Set spending expectations and school rules early; a harmless fidget can easily turn into a distraction-and-resale loop.',
        ageBand: 'Kids + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-lava-chicken',
        title: 'Lava Chicken / “chicken jockey” quotes',
        category: 'Shows & Music',
        signal: 'Kids repeating the line, singing the song, Minecraft movie callbacks, inside-joke laughter',
        meaning: 'A movie-to-game meme loop where one silly Minecraft scene and song became a shared quote across clips, gameplay, and kid conversations.',
        parentTranslation: 'This is less about plot and more about having a loud, low-stakes phrase that everyone instantly recognizes.',
        askPrompt: 'Is the joke still funny because of the movie, the song, or just because everyone can yell it?',
        watchOut: 'A good moment for basic “fun without disruption” boundaries if the quote starts taking over class, cars, or movie nights.',
        ageBand: 'Kids + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
    ],
  },
  {
    id: 'feed-2026-05-22',
    isoDate: '2026-05-22',
    date: 'May 22, 2026',
    displayDate: '05/22 Friday',
    trends: [
      {
        id: 'digest-italian-brainrot',
        title: 'Italian brainrot animals',
        category: 'Memes & Slang',
        signal: 'Absurd animal-character names, surreal edits, repeated voices and catchphrases',
        meaning: 'A short-form video meme cluster built around intentionally strange characters and repetition.',
        parentTranslation: 'It is usually nonsense humor, but kids may treat knowing the names as a social badge.',
        askPrompt: 'Which character is funniest, and which one is already annoying?',
        watchOut: 'Good opening for a quick talk about when algorithmic clips stop being funny and become automatic scrolling.',
        ageBand: 'Tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-grow-a-garden',
        title: 'Grow a Garden',
        category: 'Games',
        signal: 'Roblox gardening, pets, seeds, trading, timed check-ins',
        meaning: 'A cozy collection/progression game loop where kids compare gardens, rare items, and progress.',
        parentTranslation: 'Less about gardening than status, scarcity, and “I need to check my stuff.”',
        askPrompt: 'What is the rarest thing people are trying to get?',
        watchOut: 'Watch timed rewards, trading pressure, and requests for Robux or private-server play.',
        ageBand: 'Kids + tweens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
      {
        id: 'digest-sephora-kids',
        title: 'Sephora kids',
        category: 'Style',
        signal: 'Skincare wishlists, product routines, tween beauty hauls',
        meaning: 'Kids and tweens copying beauty/influencer routines earlier than parents may expect.',
        parentTranslation: 'The trend mixes identity play, peer status, influencer marketing, and expensive products.',
        askPrompt: 'Which products are actually useful, and which ones are just popular online?',
        watchOut: 'Check ingredient safety, body-image pressure, spending, and whether routines are age-appropriate.',
        ageBand: 'Tweens + teens',
        status: 'New to me',
        pinned: false,
        updated: 'Public feed',
      },
    ],
  },
];
